<?php
// Generated by Zend Framework 2
return array(
    'SimpleClasses\Calculator'             => __DIR__ . '/SimpleClasses/Calculator.php',
    'SimpleClass\Grade'                    => __DIR__ . '/SimpleClasses/Grade.php',
    'SimpleClasses\NullParameterException' => __DIR__ . '/SimpleClasses/NullParameterException.php',
);